import dotenv from 'dotenv';
dotenv.config();

const { PORT, MONGO_URI, JWT_SECRET, JWT_EXPIRES_IN, NODE_ENV, BACKEND_URL,
  CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET } = process.env;

export { PORT, MONGO_URI, JWT_SECRET, JWT_EXPIRES_IN, NODE_ENV, BACKEND_URL,
  CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET };


